# Generated by Django 3.1.2 on 2020-10-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='duraiton',
            new_name='duration',
        ),
    ]
